/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Appointment = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'preferredDate' : IDL.Int,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'department' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const Department = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Doctor = IDL.Record({
  'name' : IDL.Text,
  'experience' : IDL.Text,
  'specialty' : IDL.Text,
  'qualification' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'message' : IDL.Text,
  'patientName' : IDL.Text,
  'rating' : IDL.Nat,
});
export const Stats = IDL.Record({
  'beds' : IDL.Nat,
  'patients' : IDL.Nat,
  'doctors' : IDL.Nat,
  'years' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addDepartment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addDoctor' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addTestimonial' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'bookAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAllContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
  'getAllDepartments' : IDL.Func([], [IDL.Vec(Department)], ['query']),
  'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'updateStats' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Appointment = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'preferredDate' : IDL.Int,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'department' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const Department = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Doctor = IDL.Record({
    'name' : IDL.Text,
    'experience' : IDL.Text,
    'specialty' : IDL.Text,
    'qualification' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'message' : IDL.Text,
    'patientName' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const Stats = IDL.Record({
    'beds' : IDL.Nat,
    'patients' : IDL.Nat,
    'doctors' : IDL.Nat,
    'years' : IDL.Nat,
  });
  
  return IDL.Service({
    'addDepartment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addDoctor' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'addTestimonial' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'bookAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAllContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
    'getAllDepartments' : IDL.Func([], [IDL.Vec(Department)], ['query']),
    'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'updateStats' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };