/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'name' : string,
  'email' : string,
  'message' : string,
  'preferredDate' : bigint,
  'timestamp' : bigint,
  'phone' : string,
  'department' : string,
}
export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface Department { 'name' : string, 'description' : string }
export interface Doctor {
  'name' : string,
  'experience' : string,
  'specialty' : string,
  'qualification' : string,
}
export interface Stats {
  'beds' : bigint,
  'patients' : bigint,
  'doctors' : bigint,
  'years' : bigint,
}
export interface Testimonial {
  'message' : string,
  'patientName' : string,
  'rating' : bigint,
}
export interface _SERVICE {
  'addDepartment' : ActorMethod<[string, string], undefined>,
  'addDoctor' : ActorMethod<[string, string, string, string], undefined>,
  'addTestimonial' : ActorMethod<[string, string, bigint], undefined>,
  'bookAppointment' : ActorMethod<
    [string, string, string, string, bigint, string],
    string
  >,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAllContacts' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllDepartments' : ActorMethod<[], Array<Department>>,
  'getAllDoctors' : ActorMethod<[], Array<Doctor>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getStats' : ActorMethod<[], Stats>,
  'submitContactForm' : ActorMethod<[string, string, string, string], string>,
  'updateStats' : ActorMethod<[bigint, bigint, bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];